repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 26.1.0
    hooks:
      - id: black
        args: [
          '--line-length=120',
          '--skip-string-normalization',
        ]

  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args: [
          '--line-length=120',
          '--profile=black',
          '--filter-files',
        ]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-bugbear',  # B
          'flake8-builtins',  # A
          'flake8-comprehensions',  # C4
          'flake8-debugger',  # T1
          'flake8-print',  # T2
        ]
        args: [
          '--select=E,W,F,C,B,A,C4,T1,T2',
          '--ignore=E203,W503,B008,B305,A003',
          '--max-complexity=10',
          '--max-line-length=120',
        ]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: insert-license
        files: \.py$
        args: [
          '--license-filepath=COPYRIGHT',
          '--comment-style=#',
          '--use-current-year',
        ]
