name: HDC ci/cd pipeline

on:
  push:
    branches:
      - hdc
  pull_request:
    branches:
      - hdc

jobs:
  run_tests_hdc:
    uses: PilotDataPlatform/shared-ci-tools/.github/workflows/pilotcli_hdc.yml@iebh-286
    with:
      min_coverage_percent: 99

      #  build_and_publish_hdc:
      #    needs: [run_tests_hdc]
      #    uses: PilotDataPlatform/shared-ci-tools/.github/workflows/reusable_build_and_publish_hdc.yml@main
      #    with:
      #      matrix_config: '["alembic","auth"]'
      #      docker_registry: 'docker-registry.ebrains.eu'
      #      service_name: 'auth'
      #    secrets: inherit
      #
      #  deploy_hdc:
      #    needs: [build_and_publish_hdc]
      #    uses: PilotDataPlatform/shared-ci-tools/.github/workflows/reusable_trigger_deployment_hdc.yml@main
      #    with:
      #      hdc_service_name: 'auth'
      #    secrets: inherit
